// app/(admin)/events/[eventId]/sessions/new/page.tsx
'use client';
import { useState } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { Loader2, ChevronLeft } from 'lucide-react';
import Link from 'next/link';

export default function NewSessionPage() {
  const router = useRouter();
  const params = useParams();
  const eventId = params.eventId as string;
  const supabase = createClient();

  const [name, setName] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!name.trim()) {
      setError('Session name is required.');
      return;
    }
    setLoading(true);
    setError('');

    // Insert session – QR token is generated by the database trigger or we can insert manually
    const { data: session, error: insertError } = await supabase
      .from('sessions')
      .insert({ event_id: eventId, name: name.trim() })
      .select('id')
      .single();

    if (insertError || !session) {
      setError(insertError?.message || 'Failed to create session');
      setLoading(false);
      return;
    }

    router.push(`/events/${eventId}/sessions/${session.id}`);
  }

  return (
    <div className="mx-auto max-w-md space-y-5 p-4 lg:p-6">
      <div className="flex items-center gap-3">
        <Link href={`/events/${eventId}`} className="btn-ghost p-2">
          <ChevronLeft className="h-4 w-4" />
        </Link>
        <h1 className="text-xl font-semibold text-gray-900">Add session</h1>
      </div>

      <form onSubmit={handleSubmit} className="card space-y-4 p-6">
        <div>
          <label className="label">Session name *</label>
          <input
            type="text"
            required
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="e.g. Workshop – Group A"
            className="input-base"
          />
        </div>
        {error && <p className="text-xs text-red-600">{error}</p>}
        <button type="submit" disabled={loading} className="btn-primary w-full">
          {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Create session'}
        </button>
      </form>
    </div>
  );
}